"""Initial migration

Revision ID: bc97bda5c574
Revises: ef2ca2d87da5
Create Date: 2024-11-20 15:23:16.297081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc97bda5c574'
down_revision: Union[str, None] = 'ef2ca2d87da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_otp_expiration'), 'users', ['otp_expiration'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_otp_expiration'), table_name='users')
    op.drop_column('users', 'otp_expiration')
    # ### end Alembic commands ###
